### PR TITLE
Fix: no possibility to name snitch with the name that contains space symbols

### PR DESCRIPTION
**Pull request by Aleksey-Terzi**
If snitch's name should contain the space symbol then the name should be enclosed in double quotes.
For example:
`/janame world 300 100 300 "This is my snitch"`
`/janame "This is another snitch"`

### CODE REVIEW

**Review by Diet-Cola — APPROVED** [review]

**Comment by wingzero54** [comment]
Sorry I did not catch this before, but we should not allow renaming snitches in different worlds. You should have to travel to the other dimension if you want to rename your snitches there. Allowing you to play remotely in other dimensions is a step too far.

**Comment by awoo-civ** [comment]
Snitch names are inconsequential, which is why this change was requested in the first place. I don't see the distinction between a player renaming a snitch 10k away from them and renaming one in the Nether.

**Comment by Aleksey-Terzi** [comment]
I'm starting to think that the idea of remote renaming is a mistake.

**Comment by Aleksey-Terzi** [comment]
**world** parameter has been removed.
The new syntax:
```
/janame [x y z] <name>
```

**Pull request closed without merging**
