### PR TITLE
Issue #23: [Regression] /jainfo arguments don't work

### PR DESCRIPTION
**Pull request by Aleksey-Terzi**
/jainfo now supports three modes:
1. /jainfo - the same as it worked before
2. /jainfo [page_number] [censor] [action=action_type] [player=player_name] - show info by filter
3. /jainfo next - show the next page

Notes:
1. action_type - is the full or partial name of the action
2. player-name - is the full or partial name of the player who made this action
3. censor - the option which means that instead of coordinates will be shown [*** *** ***]

### CODE REVIEW

**Review by Diet-Cola — APPROVED** [review]
Cool stuff, my only thing is this conflicting with https://github.com/CivMC/JukeAlert/pull/15 which I think we should merge even though it provides no real difference to players

**Comment by Aleksey-Terzi** [comment]
Let's first merge #15 and then I will merge CivMC/master into this PR
#15 is really important, it makes difference for developers :)

**Comment by wingzero54** [comment]
#15 was closed, is there still a desire to wait to merge this?

**Comment by Aleksey-Terzi** [comment]
No, there is no need to wait for #15 anymore.
I suggest merging it whenever it will be possible.

**Pull request merged**
